apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName }}-secrets"
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "kestra-github-bot.labels" . | nindent 4 }}
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
  bot-cert.pem: {{ .Values.githubAppCertificateKey }}
