appName: "kestra-github-bot"
replicas: 1
githubAppId: 717113
githubAppCertificateKey: "" # base64 encoded string of your github app certificate
image:
  repository: "anaselmhamdi/kestra-github-bot"
  tag: "latest"
  pullPolicy: "Always"
kestraServiceUrl: http://kestra-service.kestra:8080
port: 5000
nodeSelector: {}
service:
  annotations: {}
  type: ClusterIP
ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts: []
  # - host: chart-example.local
  #   paths:
  #   - path: /
  #     pathType: ImplementationSpecific

  tls: []
  # - secretName: chart-example-tls
  #   hosts:
  #   - chart-example.local